### PR TITLE
Fix windows OnJump and AirAccelerate

### LINKED ISSUE #36: Crashes after CSGO Updated
👀

### PR DESCRIPTION
**Pull request by Szwagi**
Resolves #36

### CODE REVIEW

**Review by Sikarii — APPROVED** [review]

**Comment by zer0k-z** [comment]
OnJump works but the signature is not unique, so it might break in the future. The unique sig is way too long...

AA is ok!

**Comment by Szwagi** [comment]
> 

The Windows compiler/linker seems to put everything in source order so I thought it'd be an ok compromise considering that unique sig length.

**Comment by zealain** [comment]
If the unique one is really too long to handle, do we even have a choice? Idk how long the unique one is and what problems it would bring.

**Comment by zer0k-z** [comment]
Yeah I tried to automatically create an unique one and it's so long that the game couldn't find it somehow... It has a lot of wildcarded things though, so if I manually make a signature without those wildcards I should be able to find a shorter unique signature, but then it's more prone to break in the next update.

**Comment by zealain** [comment]
I'll just merge it like this, then. Both versions might break so it shouldn't matter too much which we use I guess.

**Pull request merged**
